java -jar -Duser.language=ru -Duser.region=RU build/libs/neural_network-1.0.jar ^
--model C:/sources/neural_network/src/test/resources/test_model_real.xlsx ^
--trainSetFile C:/sources/neural_network/src/test/resources/trainingSetReal.xlsx ^
--trainingOutputFile C:/sources/neural_network/build/model.xlsx ^
--trainingTestSetFile C:/sources/neural_network/src/test/resources/testSetReal.xlsx ^
--trainingTestOutputFile C:/sources/neural_network/build/test_output.xlsx ^
--trainingAccuracy 0.0000001 ^
--trainingEpochs 10 ^
--trainingEpochsBetweenTest 5 ^
--statisticsFile C:/sources/neural_network/build/statistics.xlsx ^
--normalizedTrainSetFile C:/sources/neural_network/build/normalized_training_set.xlsx